= Building a custom collector
:toc: right

== Introduction

Collectors are implemented as standard XP applications. They essentially consist of two main components:

Form:: A React based user interface that enable search administrators to instruct the collector in it's specific activities.

Task:: Code that performs the actual retrieval of content for indexing.

This section will guide you through the basic steps of building your own custom collector.

== Step 1: Create application

Use Enonic CLI to create an application based on the vanilla starter:

	enonic project create -r starter-collector

The starter ships with the essential setup required for any collector:

=== Dependencies

.build.gradle
[source,java]
----
dependencies {
	include 'com.enonic.lib:lib-explorer:2.1.2'
}
----

NOTE: Remember to use a version of the library that is equal to or newer than the version of Explorer you are using.


=== Register / Unregister

In order for Explorer to detect available collectors, each collector needs to register, and un.register itself:


.main.es
[source,java]
----
import {register} from '/lib/explorer/collector/register';
import {unregister} from '/lib/explorer/collector/unregister';

register({
	appName: app.name,
	collectTaskName: 'collect',
	configAssetPath: 'react/Collector.esm.js',
	displayName: 'My collector'
});

__.disposer(() => {
	unregister({
		appName: app.name,
		collectTaskName: 'collect'
	});
});
----

== Step 2: React form

The starter also provides the essential build system for the React-based user interface.

Some important ingredients that enable this are:

- node-gradle-plugin
- webpack
- babel
- node_modules
  * @enonic/webpack-esm-assets
  * @enonic/webpack-server-side-js

=== React component

In order for your collector's configuration user interface to work in Explorer you must provide a React component.
Any react component type should be supported, but all examples are functional (since that is the current status quo of react).

The component receives three props from Explorer:
. explorer - static information like contentTypes, fields and sites
. onChange - function you should call everytime you change values
. values - object to store your collectors configuration in


==== explorer object

This object contains information from Explorer about the collector context. The information can be used to make dropdowns in your collectors configuration.

==== onChange function

Every time a form field value changes you should should write the change to the values object.
And every time the values object changes you should call the onChange function.

Here is one way to achieve this:

[source,javasript]
----
React.useEffect(() => {
	if (onChange) {
		onChange({
			dirty,
			isValid,
			values
		});
	}
}, [values]);
----

Notice the onChange function takes three named parameters.

. dirty - set this to true when the values object doesn't match the initially received values object.
. isValid - set this to false when form validation fails.
. values - your collector configuration object.

==== values object

This is where you store any configuration you want to use later in the collector task.

== Step 3: Collector task

The actual code to retrieve and return content for indexing is implemented using https://developer.enonic.com/docs/xp/stable/framework/tasks[named tasks].


The most important parts of a collector are:

Progress reporting:: TODO

CRUD:: TODO

Journal:: TODO


The complexity of a collector may vary, but as to provide a basic idea, the starter includes a simple example:

.src/resources/tasks/collect.xml
[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<task>
	<description>Collect</description>
	<form>
		<input name="name" type="TextLine">
			<label>Name</label>
			<occurrences minimum="1" maximum="1"/>
		</input>
		<input name="collectorId" type="TextLine">
			<label>Collector ID</label>
			<occurrences minimum="1" maximum="1"/>
		</input>
		<input name="configJson" type="TextLine">
			<label>Config JSON</label>
			<occurrences minimum="1" maximum="1"/>
		</input>
	</form>
</task>
----

.src/resources/tasks/collect.es
[source,javascript]
----
import {Collector} from '/lib/explorer/collector'; <--1-->

export function run({name, collectorId, configJson}) { <--2-->
	const collector = new Collector({name, collectorId, configJson}); <--3-->

	if (!collector.config.uri) { <--4-->
		throw new Error('Config is missing required parameter uri!');
	}

	collector.start(); <--5-->

	const {
		uri,
		object: {
			someNestedProperty
		}
	} = collector.config; <--6-->

	while(somethingToDo) {
		if (collector.shouldStop()) { break; } <--7-->

		try {
			const {text, title} = doSomethingThatMayFail(); <--8-->

			collector.persistDocument({
				text,
				title,
				uri
			}); <--9-->

			collector.addSuccess({uri}); <--10-->

		} catch (e) {

			collector.addError({uri, message: e.message}); <--11-->

		}
	} // while somethingToDo

	// Perhaps delete documents that are no longer found...

	collector.stop(); <--12-->

} // export function run
----

<1> Import the Collector class
<2> The collect task gets passed three named parameters.
<3> Construct a Collector instance.
<4> Validate the configuration object.
<5> Start the collector. Sets startTime and more.
<6> Fetch configuration properties you need from the collector.config object.
<7> Check if someone has clicked the STOP button.
<8> This is where you collect the data you want to persist.
<9> Persist the collected data.
<10> Make a journal entry that collecting data from uri was a success.
<11> Make a journal entry that an error prevented collecting data from uri.
<12> Stop the collector. Sets endTime and more.


== Step 4: Deploy and test

TODO
