= Interfaces
:toc: right
:imagesdir: images

== Introduction

Your collected data can be exposed by defining search interfaces.
Essentially, a search interface allows you to select which collections and synonyms to combine,
as well as the ability to tune and boost your search down to field level.

== Interfaces table

The table will show a list of the interfaces.

Each row represents an interface.

By default a row will show:

* An *[Edit]* button, to configure the interface.

* The name of the interface.

* How many collection that interface searches.

* A *[Search]* button, to test the interface.

* A *[Copy]* button, in case you want to make a similar interface.

If you toggle 'Show all fields', each row will also show:

* Which collections that interface searches.

* Which fields that interface searches.

* Which Synonyms are used.

* Which Stopwords are used.

* A *[Delete]* button to open a dialog to confirm deletion of an interface.

== New/Edit

=== Name

Each interface needs a unique name.

NOTE: In order to keep API's consistent the name is limitied to the regexp /^[a-z][a-z0-9_]*$/.

CAUTION: If you try to input a name which is already in use, you will get a form validation error and will be unable to create or rename the interface.

=== Collections

You need to specify at least one collection to include in the search.

=== Fields

Select which fields should be searched and adjust the boosting of them.

=== Stop-words

The search string is split, by unicode boundaries, into words,
then each word matching a stop word will be removed from the search string.

This all happens before the synonyms stage.

CAUTION: Be careful when adding stop words, it may quickly lead to an empty search string and no search results.

=== Synonyms

You may select multiple "thesauri" of synonyms to "decorate" the query with.

First any <<#_stop_words, Stop-words>> are removed,
then the remaining search string is used to query for synonyms,
matches are used to decorate the main query.
