= Interface GraphQL API
:toc: right
:toclevels: 4

== Endpoint

The API is by default available on http://localhost:8080/webapp/com.enonic.app.explorer/interfaces/api/v1

For public use, you may configure a vhost to expose it on a custom URL, for instance to enable it on company.com/searchapi, use the following vhost setup:

.com.enonic.xp.web.vhost.cfg
[source,cfg]
----
enabled = true

mapping.interfaceApi.host = company.com
mapping.interfaceApi.source = /searchapi
mapping.interfaceApi.target = /webapp/com.enonic.app.explorer/interfaces/api/v1
----

== Authorization

In order to access the *Interface GraphQL API* you must first create an <<../admin/apiKeys#, API-Key>>, and make sure it has read access to the specified interface.

TIP: You do not have to give individual access to collections within the interface.

Then you must provide that API-key in the *Authorization* header when you do any http request against the API. For example if you have an API-key with the key "mySecretKey", the Authorization header must look like this:

 Authorization: Explorer-Api-Key mySecretKey

== GraphQL browser

The API is self-documented, and can be tested directly using the Query tester in Explorer Admin

To test the public endpoint directly, we recommend using a tool like a browser extension like https://chrome.google.com/webstore/detail/altair-graphql-client/flnheeellpciglgpaodhkhmapeljopja[the Altair GraphQL client]. 

NOTE: The API key can be set by opening the h