= Client application
:toc: right

== Introduction

Include the library in your application as documented in the <<library#include,library>> documentation.

== Selecting interface

There are numerous ways to pick an interface, using a custom selector is a pretty good solution.

=== Custom selector

The Explorer <<admin#,administration>> application provides a service that can be used by a custom selector in a site application.

.controller.xml
[source,xml]
----
<input name="interface" type="CustomSelector">
	<label>Interface</label>
	<occurrences minimum="1" maximum="1"/>
	<config>
		<service>interfaceSelector</service>
	</config>
</input>
----

The service can currently only be accessed with any of these roles:

* Content Manager Administrator (cms.admin)
* Content Manager App (cms.cm.app)
* Content Manager Expert (cms.expert)
* Administrator (system.admin)
* Administration Console Login (system.admin.login)

== Providing a search result

There are numerous ways to provide a search result.

Perhaps you want to provide a JSON service to be used with a react frontend, or do a static HTML page by rendering server-side.

Common to all solutions is that you have to call the search function, and perhaps manipulate the result to your liking.

Below is an example of this:

.controller.es
[source,java]
----
import {search} from '/lib/explorer/search';

export function get({
	params
}) {
	const {
		facetCategories,
		pages,
		pagination,
		hits,
		removedStopWords,
		synonymsObj,
		total = 0
	} = search({
		clearCache,
		//count: 10,
		facets: {
			language: params.language,
			'information-type': params['information-type'],
			source: params.source
		},
		interface: interfaceName,
		locale,
		name,
		page,
		searchString
	});
}
----
