= Collector application
:toc: right

== Introduction

Include the library in your application as documented in the <<library#include,library>> documentation.

In order for a collector to work it needs to provide 2 resources:

. A <<_react_bundle, React bundle>> using semantic-ui-react-formik-functional.
. A <<_task,task>> that does the collecting.

In order for the main <<adin#,Explorer>> application to know where these resources is located a collector application needs to register itself:

== Register / unregister
.main.es
[source,java]
----
import {register} from '/lib/explorer/collector/register';
import {unregister} from '/lib/explorer/collector/unregister';

register({
	appName: app.name,
	collectTaskName: 'collect',
	configAssetPath: 'react/Collector.esm.js',
	displayName: 'My collector'
});

__.disposer(() => {
	unregister({
		appName: app.name
	});
});
----

== React bundle

Setting up a build system to provide the react bundle can be quite complex.

Thus we have made a starter-collector for you to use and learn from.

Some important ingredients are:

- node-gradle-plugin
. webpack
. babel
. node_modules
.. @babel/preset-env
.. @babel/preset-react
.. @purtuga/esm-webpack-plugin
.. @h3t/semantic-ui-react-formik-functional

=== React component

In order for your collector's configuration user interface to work in Explorer you must provide a React component.
Any react component type should be supported, but all examples are functional (since that is the current status quo of react).

The component receives three props from Explorer:
. explorer - static information like contentTypes, fields and sites
. onChange - function you should call everytime you change values
. values - object to store your collectors configuration in


==== explorer object

This object contains information from Explorer about which contentTypes, fields and sites exists.
The information can be used to make dropdowns in your collectors configuration.

==== onChange function

Every time a form field value changes you should should write the change to the values object.
And every time the values object changes you should call the onChange function.

Here is one way to achieve this:

[source,javasript]
----
React.useEffect(() => {
	if (onChange) {
		onChange({
			dirty,
			isValid,
			values
		});
	}
}, [values]);
----

Notice the onChange function takes three named parameters.

. dirty - set this to true when the values object doesn't match the initially received values object.
. isValid - set this to false when form validation fails.
. values - your collector configuration object.

==== values object

This is where you store any configuration you want to use later in the collector task.

== Task

Developing a task to collect data can also be quite complex.

Have a look at the app-collector-simple to see an example.

Some important ingredients are:

- Progress
. Create/modify/delete
. Journal
