= Upgrading
:toc: right
:toclevels: 5

WARNING: Make sure you have snapshots, or a backup of your Explorer data available before upgrading.

When the explorer application starts, it will automatically check if migration steps are required.

Any migrations that requires user input will be initiated via UI.

== From 1.x -> 2.x

After installing Explorer 2.0, it will automatically initiate a migration of all of your old data.

When the automated upgrade is complete, a manual step will follow

=== Synonyms 2.0

In order for the legacy synonyms to work in Explorer 2.0, Explorer needs to know which language(s) the old synonyms are written in. This is needed to apply optimal stemming at index time.

. Go to the Synonyms page and edit your Thesauri.
First you pick which language(s) that Thesaurus will consist of. You may add more languages later.
+
Whatever language(s) you have choosen are now available in the *from* and *to* language dropdowns.
+
Once you have filled those in, you can click btn:[Migrate], and the magic will happen :)
Once that's done click the *[Save]* button.

. Repeat this step for each Thesauri until they are all migrated.

NOTE: Your old Thesauri may have been a "jungle" of multiple languages. Each synonym has a language dropdown, so it's easy to change language on it.

=== Upgrading collectors

We have created a dedicated document with details on how to <<collectors/upgrade#, upgrade a custom collector>>.